# **Introdução ao Pandas**

Pandas é uma biblioteca de código aberto em Python que oferece estruturas de dados de alto desempenho e ferramentas de análise de dados. Ela é amplamente utilizada na ciência de dados e em análises estatísticas devido à sua eficiência, flexibilidade e facilidade de uso. Desenvolvida por Wes McKinney em 2008, a Pandas tem se tornado a principal escolha para manipulação e análise de dados em Python.

A importância da biblioteca Pandas para a ciência de dados é imensa, e isso se deve a várias razões:

+ **Estruturas de Dados Flexíveis:** A Pandas fornece duas estruturas de dados principais: Series e DataFrame. A Series é uma matriz unidimensional rotulada capaz de armazenar qualquer tipo de dado. O DataFrame é uma estrutura de dados tabular bidimensional semelhante a uma planilha do Excel, onde cada coluna pode ser de um tipo diferente. Essas estruturas de dados são altamente flexíveis e permitem manipular e analisar dados de maneira eficaz.

+ **Manipulação de Dados:** Pandas oferece uma ampla gama de funcionalidades para manipulação de dados, incluindo filtragem, seleção, ordenação, agrupamento e fusão de dados. Com métodos poderosos e intuitivos, os usuários podem manipular conjuntos de dados de maneira eficiente, realizando operações complexas em apenas algumas linhas de código.

+ **Limpeza de Dados:** Antes de qualquer análise de dados, é crucial limpar e preparar os dados. Pandas oferece ferramentas para lidar com dados ausentes, duplicados, inconsistentes e até mesmo outliers. Isso permite que os cientistas de dados preparem os dados para análise de forma rápida e eficiente.

+ **Integração com Outras Ferramentas:** Pandas é frequentemente utilizada em conjunto com outras bibliotecas populares de ciência de dados em Python, como NumPy, Matplotlib, Seaborn e Scikit-learn. Essa integração perfeita permite uma análise de dados completa, desde a limpeza e manipulação até a visualização e modelagem.

+ **Visualização de Dados:** Embora não seja uma biblioteca de visualização, Pandas se integra facilmente com outras bibliotecas de visualização de dados em Python, permitindo que os usuários criem gráficos e plots informativos para explorar e comunicar seus resultados.

+ **Eficiência Computacional:** Pandas é altamente otimizada para desempenho e escalabilidade. Ela é construída sobre a biblioteca NumPy, o que significa que muitas operações são executadas em código de baixo nível, proporcionando desempenho excepcional, mesmo para conjuntos de dados grandes.

**Importando a biblioteca**

In [1]:
import pandas as pd
pd.options.mode.copy_on_write = True

**Carregando os dados**

O método `pd.read_csv()` é uma função da biblioteca Pandas em Python que permite ler arquivos CSV (Comma-Separated Values) e convertê-los em um DataFrame do Pandas. Ele é usado para importar dados de arquivos CSV diretamente para o ambiente de trabalho do Python para análise de dados.

Quando você chama `pd.read_csv('nome_do_arquivo.csv')`, o Pandas lê o arquivo CSV especificado e cria um DataFrame, onde cada linha do arquivo CSV é uma linha no DataFrame e os valores separados por vírgula em cada linha são automaticamente divididos em colunas.

Este método oferece uma variedade de parâmetros opcionais para personalizar a leitura do arquivo CSV, permitindo que você especifique separadores de campos diferentes de vírgula, tratamento de valores ausentes, tipos de dados para colunas, entre outros.

Em resumo, o método `pd.read_csv()` é uma ferramenta essencial para importar dados de arquivos CSV para o Python e começar a trabalhar com eles usando Pandas.

In [2]:
df = pd.read_csv("./top10s.csv",
                 encoding="ISO-8859-1")

**Visualizando a estrutura do DataFrame**

O método `df.head()` é uma função da biblioteca Pandas em Python que é utilizada para visualizar as primeiras linhas de um DataFrame. Quando chamado em um DataFrame (`df`), ele retorna por padrão as cinco primeiras linhas do DataFrame, permitindo uma rápida visualização dos dados. Isso é útil para ter uma ideia inicial da estrutura e do conteúdo dos dados, especialmente em conjuntos de dados grandes. Além disso, é possível passar um argumento opcional para especificar o número de linhas a serem exibidas, como por exemplo `df.head(4)` para mostrar as dez primeiras linhas. Em suma, o método `df.head()` é uma ferramenta essencial para a exploração inicial de dados em Pandas.

In [3]:
df.head(4)

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,80,217,19,4,83
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,64,263,24,23,82
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,71,200,10,14,80
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,71,295,0,4,79

**Visualizando as informações do DataFrame**

O método `df.info()` é uma função fundamental da biblioteca Pandas em Python, usada para fornecer um resumo conciso e informativo sobre um DataFrame. Quando chamado em um DataFrame, o método `df.info()` exibe informações essenciais, como o tipo de dados de cada coluna, a quantidade de valores não nulos em cada coluna e a quantidade total de memória utilizada pelo DataFrame. Essa função é útil para entender rapidamente a estrutura dos dados, identificar possíveis problemas de tipo de dados ou valores ausentes e otimizar o uso de memória. Em resumo, o método `df.info()` é uma ferramenta valiosa para a análise inicial de conjuntos de dados em Pandas.

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 603 entries, 0 to 602
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  603 non-null    int64
 1   title       603 non-null    object
 2   artist      603 non-null    object
 3   top genre   603 non-null    object
 4   year        603 non-null    int64
 5   bpm         603 non-null    int64
 6   nrgy        603 non-null    int64
 7   dnce        603 non-null    int64
 8   dB          603 non-null    int64
 9   live        603 non-null    int64
 10  val         603 non-null    int64
 11  dur         603 non-null    int64
 12  acous       603 non-null    int64
 13  spch        603 non-null    int64
 14  pop         603 non-null    int64
dtypes: int64(12), object(3)
memory usage: 70.8+ KB

In [5]:
df2 = pd.read_csv("./SpotifyTopSongsByCountry - May 2020.csv",
                  encoding="ISO-8859-1")

In [6]:
df2.head()

,Country,Continent,Rank,Title,Artists,Album,Explicit,Duration
0,Global,Global,1,Rain On Me (with Ariana Grande),"Lady Gaga, Ariana Grande",Rain On Me (with Ariana Grande),0,3:02
1,Global,Global,2,Blinding Lights,The Weeknd,After Hours,0,3:20
2,Global,Global,3,ROCKSTAR (feat. Roddy Ricch),"DaBaby, Roddy Ricch",BLAME IT ON BABY,1,3:01
3,Global,Global,4,Roses - Imanbek Remix,"SAINt JHN, Imanbek",Roses (Imanbek Remix),1,2:56
4,Global,Global,5,Toosie Slide,Drake,Dark Lane Demo Tapes,1,4:07

In [7]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3150 entries, 0 to 3149
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    3150 non-null   object
 1   Continent  3150 non-null   object
 2   Rank       3150 non-null   int64
 3   Title      3150 non-null   object
 4   Artists    3150 non-null   object
 5   Album      3150 non-null   object
 6   Explicit   3150 non-null   int64
 7   Duration   3150 non-null   object
dtypes: int64(2), object(6)
memory usage: 197.0+ KB

O dtype mostra de forma mais resumida os tipos de dados de cada coluna

In [8]:
df2.dtypes

Country      object
Continent    object
Rank          int64
Title        object
Artists      object
Album        object
Explicit      int64
Duration     object
dtype: object

In [9]:
df2.select_dtypes(include="int64")

      Rank  Explicit
0        1         0
1        2         0
2        3         1
3        4         1
4        5         1
...    ...       ...
3145    46         0
3146    47         0
3147    48         0
3148    49         0
3149    50         0

[3150 rows x 2 columns]

In [10]:
df2.select_dtypes(include="object")

,Country,Continent,Title,Artists,Album,Duration
0,Global,Global,Rain On Me (with Ariana Grande),"Lady Gaga, Ariana Grande",Rain On Me (with Ariana Grande),3:02
1,Global,Global,Blinding Lights,The Weeknd,After Hours,3:20
2,Global,Global,ROCKSTAR (feat. Roddy Ricch),"DaBaby, Roddy Ricch",BLAME IT ON BABY,3:01
3,Global,Global,Roses - Imanbek Remix,"SAINt JHN, Imanbek",Roses (Imanbek Remix),2:56
4,Global,Global,Toosie Slide,Drake,Dark Lane Demo Tapes,4:07
...,...,...,...,...,...,...
3145,Vietnam,Asia,ÄÃ Tá»ªNG LÃ,VÅ©.,ÄÃ Tá»ªNG LÃ,4:20
3146,Vietnam,Asia,MÆ°á»£n RÆ°á»£u Tá» TÃ¬nh,"BigDaddy, Emily",MÆ°á»£n RÆ°á»£u Tá» TÃ¬nh,3:18
3147,Vietnam,Asia,NgÃ y Táº­n Tháº¿,"TÃ³c TiÃªn, Da LAB, Touliver",NgÃ y Táº­n Tháº¿,3:52
3148,Vietnam,Asia,Äi Äu ÄÆ°a Äi,Bich Phuong,Äi Äu ÄÆ°a Äi,3:40
3149,Vietnam,Asia,Blinding Lights,The Weeknd,After Hours,3:20

In [11]:
df2.describe()

              Rank     Explicit
count  3150.000000  3150.000000
mean     25.500000     0.348889
std      14.433161     0.476694
min       1.000000     0.000000
25%      13.000000     0.000000
50%      25.500000     0.000000
75%      38.000000     1.000000
max      50.000000     1.000000

In [12]:
df.describe()

,Unnamed: 0,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
count,603.000000,603.000000,603.000000,603.000000,603.000000,603.000000,603.000000,603.000000,603.000000,603.000000,603.000000,603.000000
mean,302.000000,2014.592040,118.545605,70.504146,64.379768,-5.578773,17.774461,52.225539,224.674959,14.326700,8.358209,66.520730
std,174.215384,2.607057,24.795358,16.310664,13.378718,2.798020,13.102543,22.513020,34.130059,20.766165,7.483162,14.517746
min,1.000000,2010.000000,0.000000,0.000000,0.000000,-60.000000,0.000000,0.000000,134.000000,0.000000,0.000000,0.000000
25%,151.500000,2013.000000,100.000000,61.000000,57.000000,-6.000000,9.000000,35.000000,202.000000,2.000000,4.000000,60.000000
50%,302.000000,2015.000000,120.000000,74.000000,66.000000,-5.000000,12.000000,52.000000,221.000000,6.000000,5.000000,69.000000
75%,452.500000,2017.000000,129.000000,82.000000,73.000000,-4.000000,24.000000,69.000000,239.500000,17.000000,9.000000,76.000000
max,603.000000,2019.000000,206.000000,98.000000,97.000000,-2.000000,74.000000,98.000000,424.000000,99.000000,48.000000,99.000000

In [13]:
df2.isna().sum()

Country      0
Continent    0
Rank         0
Title        0
Artists      0
Album        0
Explicit     0
Duration     0
dtype: int64

In [14]:
df["artist"].unique()

array(['Train', 'Eminem', 'Kesha', 'Lady Gaga', 'Bruno Mars',
       'Justin Bieber', 'Taio Cruz', 'OneRepublic', 'Alicia Keys',
       'Rihanna', 'Flo Rida', 'Mike Posner', 'Far East Movement', 'Usher',
       'Sean Kingston', 'The Black Eyed Peas', 'Adam Lambert', 'Maroon 5',
       'Neon Trees', 'Selena Gomez & The Scene', 'Enrique Iglesias',
       'Katy Perry', 'Britney Spears', '3OH!3', 'David Guetta',
       'Christina Aguilera', 'Florence + The Machine', 'Shakira',
       'Tinie Tempah', 'T.I.', 'Martin Solveig', 'Christina Perri',
       'Adele', 'Pitbull', 'Beyoncé', 'Hot Chelle Rae', 'Avril Lavigne',
       'Kanye West', 'LMFAO', 'Jessie J', 'Jennifer Lopez', 'Chris Brown',
       'Sleeping At Last', 'Nicki Minaj', 'P!nk', 'Coldplay',
       'One Direction', 'Taylor Swift', 'Carly Rae Jepsen',
       'Kelly Clarkson', 'Owl City', 'The Wanted', 'fun.',
       'Ellie Goulding', 'Gym Class Heroes', 'Avicii', 'The Script',
       'Miley Cyrus', 'Swedish House Mafia', 'Daft Punk', 'James Arthur',
       'Robin Thicke', 'Demi Lovato', 'Zedd', 'Lana Del Rey',
       'Calvin Harris', 'Drake', 'Sara Bareilles',
       'Macklemore & Ryan Lewis', 'Labrinth', 'Ne-Yo', 'Ariana Grande',
       'Justin Timberlake', 'will.i.am', 'Icona Pop', 'Fergie',
       'Little Mix', 'Emeli Sandé', 'Selena Gomez', 'Austin Mahone',
       'Jonas Brothers', 'Mariah Carey', 'Ciara', 'Jewel',
       'Kelly Rowland', 'John Legend', 'Sam Smith', 'Pharrell Williams',
       'MAGIC!', 'Passenger', 'Bastille', 'Lorde', 'John Newman',
       'Disclosure', 'Michael Jackson', '5 Seconds of Summer',
       'Iggy Azalea', 'Jason Derulo', 'The Chainsmokers', 'Birdy',
       'A Great Big World', 'Sia', 'Charli XCX', 'Lily Allen',
       'Lea Michele', 'Ed Sheeran', 'The Weeknd', 'Mark Ronson', 'Hozier',
       'Shawn Mendes', 'Mr. Probz', 'Zara Larsson', 'Fifth Harmony',
       'Clean Bandit', 'Meghan Trainor', 'Nick Jonas', 'Paloma Faith',
       'Olly Murs', 'Naughty Boy', 'Alessia Cara', 'Sigala', 'Rudimental',
       'Lost Frequencies', 'Robin Schulz', 'Lilly Wood and The Prick',
       'Wiz Khalifa', 'Alesso', 'Madonna', 'Gwen Stefani', 'Jess Glynne',
       'Hilary Duff', 'Ricky Martin', 'Jennifer Hudson', 'DNCE',
       'Martin Garrix', 'Lukas Graham', 'G-Eazy', 'Hailee Steinfeld',
       'BØRNS', 'Major Lazer', 'MØ', 'Tove Lo', 'ZAYN', 'Bebe Rexha',
       'Snakehips', 'Missy Elliott', 'Years & Years', 'Charlie Puth',
       'Janet Jackson', 'Joey Montana', 'Nelly Furtado', 'DJ Snake',
       'Kygo', 'DJ Khaled', 'Luis Fonsi', 'Camila Cabello', 'Jonas Blue',
       'CNCO', 'Cardi B', 'Alan Walker', 'Liam Payne', 'Niall Horan',
       'Cashmere Cat', 'Galantis', 'Dua Lipa', 'Silk City', 'Marshmello',
       'Halsey', 'Troye Sivan', 'Dan + Shay', 'Rita Ora', 'Harry Styles',
       'Ansel Elgort', 'J Balvin', 'N.E.R.D', 'Hayley Kiyoko', 'RedOne',
       'Lewis Capaldi', 'SHAED', 'Lizzo', 'Mabel', 'Khalid', 'R3HAB',
       'Daddy Yankee'], dtype=object)

In [15]:
df.size

9045

In [16]:
df.columns

Index(['Unnamed: 0', 'title', 'artist', 'top genre', 'year', 'bpm', 'nrgy',
       'dnce', 'dB', 'live', 'val', 'dur', 'acous', 'spch', 'pop'],
      dtype='object')

In [17]:
df.nsmallest(3, "nrgy")

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
442,443,Million Years Ago,Adele,british soul,2016,0,0,0,-60,0,0,227,0,0,0
431,432,Start,John Legend,neo mellow,2016,110,4,52,-15,9,26,310,99,4,47
255,256,Not About Angels,Birdy,neo mellow,2014,116,14,41,-10,9,23,190,97,4,56

In [18]:
df_ops = df.drop_duplicates(subset="title", keep="last")
display(df_ops)

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,80,217,19,4,83
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,64,263,24,23,82
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,71,200,10,14,80
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,71,295,0,4,79
5,6,Baby,Justin Bieber,canadian pop,2010,65,86,73,-5,11,54,214,4,14,77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598,599,Find U Again (feat. Camila Cabello),Mark Ronson,dance pop,2019,104,66,61,-7,20,16,176,1,3,75
599,600,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,2019,95,79,75,-6,7,61,206,21,12,75
600,601,"No Brainer (feat. Justin Bieber, Chance the Ra...",DJ Khaled,dance pop,2019,136,76,53,-5,9,65,260,7,34,70
601,602,Nothing Breaks Like a Heart (feat. Miley Cyrus),Mark Ronson,dance pop,2019,114,79,60,-6,42,24,217,1,7,69
602,603,Kills You Slowly,The Chainsmokers,electropop,2019,150,44,70,-9,13,23,213,6,6,67

In [19]:
df_ops.fillna(0)

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,80,217,19,4,83
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,64,263,24,23,82
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,71,200,10,14,80
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,71,295,0,4,79
5,6,Baby,Justin Bieber,canadian pop,2010,65,86,73,-5,11,54,214,4,14,77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598,599,Find U Again (feat. Camila Cabello),Mark Ronson,dance pop,2019,104,66,61,-7,20,16,176,1,3,75
599,600,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,2019,95,79,75,-6,7,61,206,21,12,75
600,601,"No Brainer (feat. Justin Bieber, Chance the Ra...",DJ Khaled,dance pop,2019,136,76,53,-5,9,65,260,7,34,70
601,602,Nothing Breaks Like a Heart (feat. Miley Cyrus),Mark Ronson,dance pop,2019,114,79,60,-6,42,24,217,1,7,69
602,603,Kills You Slowly,The Chainsmokers,electropop,2019,150,44,70,-9,13,23,213,6,6,67

In [20]:
df_ops.T

,0,1,2,3,5,6,7,8,9,10,...,593,594,595,596,597,598,599,600,601,602
Unnamed: 0,1,2,3,4,6,7,8,9,10,11,...,594,595,596,597,598,599,600,601,602,603
title,"Hey, Soul Sister",Love The Way You Lie,TiK ToK,Bad Romance,Baby,Dynamite,Secrets,Empire State of Mind (Part II) Broken Down,Only Girl (In The World),Club Can't Handle Me (feat. David Guetta),...,Call You Mine,No Guidance (feat. Drake),Antisocial (with Travis Scott),"Taki Taki (feat. Selena Gomez, Ozuna & Cardi B)",Con Calma - Remix,Find U Again (feat. Camila Cabello),Cross Me (feat. Chance the Rapper & PnB Rock),"No Brainer (feat. Justin Bieber, Chance the Ra...",Nothing Breaks Like a Heart (feat. Miley Cyrus),Kills You Slowly
artist,Train,Eminem,Kesha,Lady Gaga,Justin Bieber,Taio Cruz,OneRepublic,Alicia Keys,Rihanna,Flo Rida,...,The Chainsmokers,Chris Brown,Ed Sheeran,DJ Snake,Daddy Yankee,Mark Ronson,Ed Sheeran,DJ Khaled,Mark Ronson,The Chainsmokers
top genre,neo mellow,detroit hip hop,dance pop,dance pop,canadian pop,dance pop,dance pop,hip pop,barbadian pop,dance pop,...,electropop,dance pop,pop,electronic trap,latin,dance pop,pop,dance pop,dance pop,electropop
year,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,...,2019,2019,2019,2019,2019,2019,2019,2019,2019,2019
bpm,97,87,120,119,65,120,148,93,126,128,...,104,93,152,96,94,104,95,136,114,150
nrgy,89,93,84,92,86,78,76,37,72,87,...,70,45,82,80,87,66,79,76,79,44
dnce,67,75,76,70,73,75,52,48,79,62,...,59,70,72,84,74,61,75,53,60,70
dB,-4,-5,-3,-4,-5,-4,-6,-8,-4,-4,...,-6,-7,-5,-4,-3,-7,-6,-5,-6,-9
live,8,52,29,8,11,4,12,12,7,6,...,34,16,36,6,4,20,7,9,42,13
val,80,64,71,71,54,82,38,14,61,47,...,52,14,91,62,61,16,61,65,24,23
dur,217,263,200,295,214,203,225,216,235,235,...,218,261,162,213,181,176,206,260,217,213
acous,19,24,10,0,4,0,7,74,13,3,...,20,12,13,16,17,1,21,7,1,6
spch,4,23,14,4,14,9,4,3,4,3,...,3,15,5,23,5,3,12,34,7,6
pop,83,82,80,79,77,77,77,76,73,73,...,81,81,78,77,76,75,75,70,69,67

In [21]:
df_ops.sample(n=10)

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
364,365,Love Yourself,Justin Bieber,canadian pop,2016,100,38,61,-10,28,52,234,84,44,83
41,42,Doesn't Mean Anything,Alicia Keys,hip pop,2010,104,41,71,-7,10,10,273,4,3,57
185,186,Made In The USA,Demi Lovato,dance pop,2013,87,86,58,-4,32,59,196,0,4,60
318,319,Easy Love,Sigala,dance pop,2015,124,94,68,-4,12,65,230,18,6,67
194,195,Take Back the Night,Justin Timberlake,dance pop,2013,107,66,59,-5,64,33,353,4,16,54
211,212,Stay With Me,Sam Smith,pop,2014,84,42,42,-6,11,18,173,59,4,85
56,57,Run the World (Girls),Beyoncé,dance pop,2011,127,90,73,-4,37,76,236,0,14,76
313,314,Lips Are Movin,Meghan Trainor,dance pop,2015,139,83,78,-5,11,95,183,5,5,68
126,127,Where Have You Been,Rihanna,barbadian pop,2012,128,85,72,-6,22,44,243,0,9,68
28,29,Teenage Dream,Katy Perry,dance pop,2010,120,80,72,-5,13,59,228,2,4,63

In [22]:
len(df_ops)

584

In [23]:
df.query("artist == 'Ariana Grande'")

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
171,172,The Way,Ariana Grande,dance pop,2013,82,88,65,-3,8,86,227,29,11,68
221,222,Problem,Ariana Grande,dance pop,2014,103,81,66,-5,16,63,194,2,15,75
287,288,Love Me Harder,Ariana Grande,dance pop,2015,99,71,47,-4,8,24,236,1,3,76
291,292,Break Free,Ariana Grande,dance pop,2015,130,70,69,-5,20,28,215,1,5,75
323,324,Focus,Ariana Grande,dance pop,2015,100,88,67,-6,44,79,211,27,24,66
368,369,Into You,Ariana Grande,dance pop,2016,108,73,62,-6,14,37,244,2,11,80
381,382,Dangerous Woman,Ariana Grande,dance pop,2016,134,60,66,-5,36,29,236,5,4,78
451,452,Side To Side,Ariana Grande,dance pop,2017,159,74,65,-6,24,61,226,5,23,80
513,514,no tears left to cry,Ariana Grande,dance pop,2018,122,71,70,-6,29,35,206,4,6,84

In [24]:
df.query("dur > 200")

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,80,217,19,4,83
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,64,263,24,23,82
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,71,295,0,4,79
4,5,Just the Way You Are,Bruno Mars,pop,2010,109,84,64,-5,9,43,221,2,4,78
5,6,Baby,Justin Bieber,canadian pop,2010,65,86,73,-5,11,54,214,4,14,77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
596,597,"Taki Taki (feat. Selena Gomez, Ozuna & Cardi B)",DJ Snake,electronic trap,2019,96,80,84,-4,6,62,213,16,23,77
599,600,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,2019,95,79,75,-6,7,61,206,21,12,75
600,601,"No Brainer (feat. Justin Bieber, Chance the Ra...",DJ Khaled,dance pop,2019,136,76,53,-5,9,65,260,7,34,70
601,602,Nothing Breaks Like a Heart (feat. Miley Cyrus),Mark Ronson,dance pop,2019,114,79,60,-6,42,24,217,1,7,69
602,603,Kills You Slowly,The Chainsmokers,electropop,2019,150,44,70,-9,13,23,213,6,6,67

In [25]:
df.query("dur < 200")

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
19,20,Your Love Is My Drug,Kesha,dance pop,2010,120,61,83,-4,9,76,187,1,10,69
31,32,My First Kiss - feat. Ke$ha,3OH!3,dance pop,2010,138,89,68,-4,36,83,192,1,8,62
32,33,Blah Blah Blah (feat. 3OH!3),Kesha,dance pop,2010,120,84,75,-3,42,52,172,8,12,62
35,36,Sexy Bitch (feat. Akon),David Guetta,dance pop,2010,130,63,81,-5,13,80,196,8,5,61
40,41,Something's Got A Hold On Me - Burlesque Origi...,Christina Aguilera,dance pop,2010,150,85,51,-4,12,72,185,47,27,58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
588,589,Talk (feat. Disclosure),Khalid,alternative r&b,2019,136,40,90,-9,6,35,198,5,13,84
591,592,All Around The World (La La La),R3HAB,big room,2019,125,86,73,-5,11,52,148,48,3,82
595,596,Antisocial (with Travis Scott),Ed Sheeran,pop,2019,152,82,72,-5,36,91,162,13,5,78
597,598,Con Calma - Remix,Daddy Yankee,latin,2019,94,87,74,-3,4,61,181,17,5,76
598,599,Find U Again (feat. Camila Cabello),Mark Ronson,dance pop,2019,104,66,61,-7,20,16,176,1,3,75

In [26]:
df.loc[df["artist"]=="Ariana Grande"]

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
171,172,The Way,Ariana Grande,dance pop,2013,82,88,65,-3,8,86,227,29,11,68
221,222,Problem,Ariana Grande,dance pop,2014,103,81,66,-5,16,63,194,2,15,75
287,288,Love Me Harder,Ariana Grande,dance pop,2015,99,71,47,-4,8,24,236,1,3,76
291,292,Break Free,Ariana Grande,dance pop,2015,130,70,69,-5,20,28,215,1,5,75
323,324,Focus,Ariana Grande,dance pop,2015,100,88,67,-6,44,79,211,27,24,66
368,369,Into You,Ariana Grande,dance pop,2016,108,73,62,-6,14,37,244,2,11,80
381,382,Dangerous Woman,Ariana Grande,dance pop,2016,134,60,66,-5,36,29,236,5,4,78
451,452,Side To Side,Ariana Grande,dance pop,2017,159,74,65,-6,24,61,226,5,23,80
513,514,no tears left to cry,Ariana Grande,dance pop,2018,122,71,70,-6,29,35,206,4,6,84

In [27]:
df.isin(["Ariana Grande", "Katy Perry"])

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
599,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
600,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
601,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
602,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [28]:
artistas = ["Ariana Grande", "Katy Perry"]
df.isin(artistas)

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
599,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
600,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
601,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
602,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [29]:
artistas = ["Ariana Grande", "Katy Perry"]
df["artist"].isin(artistas)

0      False
1      False
2      False
3      False
4      False
       ...
598    False
599    False
600    False
601    False
602    False
Name: artist, Length: 603, dtype: bool

In [30]:
artistas = ["Ariana Grande", "Katy Perry"]
df[df["artist"].isin(artistas)]

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
28,29,Teenage Dream,Katy Perry,dance pop,2010,120,80,72,-5,13,59,228,2,4,63
29,30,California Gurls,Katy Perry,dance pop,2010,125,75,79,-4,18,40,235,0,5,62
77,78,E.T.,Katy Perry,dance pop,2011,152,87,62,-5,37,76,230,2,18,66
101,102,Last Friday Night (T.G.I.F.),Katy Perry,dance pop,2011,126,81,65,-4,67,72,231,0,4,27
102,103,Firework,Katy Perry,dance pop,2011,124,83,64,-5,11,65,228,14,5,25
124,125,Part Of Me,Katy Perry,dance pop,2012,130,92,68,-5,7,77,216,0,4,71
127,128,Wide Awake,Katy Perry,dance pop,2012,160,68,51,-5,39,57,221,7,4,68
128,129,The One That Got Away,Katy Perry,dance pop,2012,134,80,69,-4,16,88,227,0,4,67
144,145,Roar,Katy Perry,dance pop,2013,180,77,55,-5,35,46,224,0,4,78
171,172,The Way,Ariana Grande,dance pop,2013,82,88,65,-3,8,86,227,29,11,68
216,217,Dark Horse,Katy Perry,dance pop,2014,132,59,65,-6,17,35,216,0,5,78
221,222,Problem,Ariana Grande,dance pop,2014,103,81,66,-5,16,63,194,2,15,75
237,238,This Is How We Do,Katy Perry,dance pop,2014,96,64,69,-6,15,80,204,2,5,66
242,243,Birthday,Katy Perry,dance pop,2014,126,67,72,-5,11,84,215,9,7,65
287,288,Love Me Harder,Ariana Grande,dance pop,2015,99,71,47,-4,8,24,236,1,3,76
291,292,Break Free,Ariana Grande,dance pop,2015,130,70,69,-5,20,28,215,1,5,75
323,324,Focus,Ariana Grande,dance pop,2015,100,88,67,-6,44,79,211,27,24,66
357,358,Legendary Lovers,Katy Perry,dance pop,2015,126,84,62,-5,8,39,224,2,8,41
368,369,Into You,Ariana Grande,dance pop,2016,108,73,62,-6,14,37,244,2,11,80
381,382,Dangerous Woman,Ariana Grande,dance pop,2016,134,60,66,-5,36,29,236,5,4,78
408,409,Rise,Katy Perry,dance pop,2016,101,64,55,-6,11,44,203,5,5,66
451,452,Side To Side,Ariana Grande,dance pop,2017,159,74,65,-6,24,61,226,5,23,80
468,469,Swish Swish,Katy Perry,dance pop,2017,120,71,84,-5,10,57,243,2,4,73
469,470,Chained To The Rhythm,Katy Perry,dance pop,2017,190,80,45,-5,20,47,238,8,17,72
485,486,Bon appétit,Katy Perry,dance pop,2017,106,79,80,-6,22,52,228,13,6,68
513,514,no tears left to cry,Ariana Grande,dance pop,2018,122,71,70,-6,29,35,206,4,6,84

In [31]:
(df["artist"]=="Katy Perry").any()

True

In [32]:
(df["artist"]=="Queen").any()

False

In [33]:
df_ops.drop(columns=["spch"], inplace=True)

In [34]:
df_ops.head()

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,pop
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,80,217,19,83
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,64,263,24,82
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,71,200,10,80
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,71,295,0,79
5,6,Baby,Justin Bieber,canadian pop,2010,65,86,73,-5,11,54,214,4,77

In [35]:
df_ops["dur"].mean()

224.63698630136986

In [36]:
df_ops.dtypes

Unnamed: 0     int64
title         object
artist        object
top genre     object
year           int64
bpm            int64
nrgy           int64
dnce           int64
dB             int64
live           int64
val            int64
dur            int64
acous          int64
pop            int64
dtype: object

In [37]:
df_ops.select_dtypes(include="int64").mean()

Unnamed: 0     304.760274
year          2014.631849
bpm            118.592466
nrgy            70.501712
dnce            64.508562
dB              -5.571918
live            17.902397
val             52.277397
dur            224.636986
acous           14.152397
pop             66.529110
dtype: float64

In [38]:
df_ops.agg({"acous": "mean",
            "dur": "max"})

acous     14.152397
dur      424.000000
dtype: float64

In [39]:
df_ops["dur"].cumsum()

0         217
1         480
2         680
3         975
5        1189
        ...
598    130292
599    130498
600    130758
601    130975
602    131188
Name: dur, Length: 584, dtype: int64

In [40]:
df_ops.sort_values(by="dur", ascending=False)

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,pop
188,189,TKO,Justin Timberlake,dance pop,2013,138,68,61,-7,43,49,424,1,58
422,423,Wish That You Were Here - From Miss Peregrine...,Florence + The Machine,art pop,2016,94,57,37,-6,13,12,403,72,57
63,64,Monster,Kanye West,chicago rap,2011,125,69,63,-6,67,10,379,0,73
162,163,Lose Yourself to Dance,Daft Punk,electro,2013,100,66,83,-8,8,67,354,8,72
194,195,Take Back the Night,Justin Timberlake,dance pop,2013,107,66,59,-5,64,33,353,4,54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581,582,Good as Hell (feat. Ariana Grande) - Remix,Lizzo,escape room,2019,96,89,67,-3,74,48,159,30,90
492,493,Reality (feat. Janieck Devy) - Radio Edit,Lost Frequencies,belgian edm,2017,122,64,73,-7,8,53,158,2,59
174,175,I Love It (feat. Charli XCX),Icona Pop,candy pop,2013,126,91,71,-3,15,82,157,1,67
591,592,All Around The World (La La La),R3HAB,big room,2019,125,86,73,-5,11,52,148,48,82
330,331,Mark My Words,Justin Bieber,canadian pop,2015,114,26,38,-9,17,52,134,88,63

In [41]:
    df_ops["year"].astype(str)

0      2010
1      2010
2      2010
3      2010
5      2010
       ...
598    2019
599    2019
600    2019
601    2019
602    2019
Name: year, Length: 584, dtype: object

In [42]:
pd.get_dummies(df, columns=["artist"])

,Unnamed: 0,title,top genre,year,bpm,nrgy,dnce,dB,live,val,...,artist_Train,artist_Troye Sivan,artist_Usher,artist_Wiz Khalifa,artist_Years & Years,artist_ZAYN,artist_Zara Larsson,artist_Zedd,artist_fun.,artist_will.i.am
0,1,"Hey, Soul Sister",neo mellow,2010,97,89,67,-4,8,80,...,True,False,False,False,False,False,False,False,False,False
1,2,Love The Way You Lie,detroit hip hop,2010,87,93,75,-5,52,64,...,False,False,False,False,False,False,False,False,False,False
2,3,TiK ToK,dance pop,2010,120,84,76,-3,29,71,...,False,False,False,False,False,False,False,False,False,False
3,4,Bad Romance,dance pop,2010,119,92,70,-4,8,71,...,False,False,False,False,False,False,False,False,False,False
4,5,Just the Way You Are,pop,2010,109,84,64,-5,9,43,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598,599,Find U Again (feat. Camila Cabello),dance pop,2019,104,66,61,-7,20,16,...,False,False,False,False,False,False,False,False,False,False
599,600,Cross Me (feat. Chance the Rapper & PnB Rock),pop,2019,95,79,75,-6,7,61,...,False,False,False,False,False,False,False,False,False,False
600,601,"No Brainer (feat. Justin Bieber, Chance the Ra...",dance pop,2019,136,76,53,-5,9,65,...,False,False,False,False,False,False,False,False,False,False
601,602,Nothing Breaks Like a Heart (feat. Miley Cyrus),dance pop,2019,114,79,60,-6,42,24,...,False,False,False,False,False,False,False,False,False,False
602,603,Kills You Slowly,electropop,2019,150,44,70,-9,13,23,...,False,False,False,False,False,False,False,False,False,False

In [43]:
df_ops.assign(energy_dance = lambda df: df["dnce"]*df["nrgy"])

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,pop,energy_dance
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,80,217,19,83,5963
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,64,263,24,82,6975
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,71,200,10,80,6384
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,71,295,0,79,6440
5,6,Baby,Justin Bieber,canadian pop,2010,65,86,73,-5,11,54,214,4,77,6278
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598,599,Find U Again (feat. Camila Cabello),Mark Ronson,dance pop,2019,104,66,61,-7,20,16,176,1,75,4026
599,600,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,2019,95,79,75,-6,7,61,206,21,75,5925
600,601,"No Brainer (feat. Justin Bieber, Chance the Ra...",DJ Khaled,dance pop,2019,136,76,53,-5,9,65,260,7,70,4028
601,602,Nothing Breaks Like a Heart (feat. Miley Cyrus),Mark Ronson,dance pop,2019,114,79,60,-6,42,24,217,1,69,4740
602,603,Kills You Slowly,The Chainsmokers,electropop,2019,150,44,70,-9,13,23,213,6,67,3080

In [44]:
df.groupby("artist")["title"].count()

artist
3OH!3                   1
5 Seconds of Summer     1
A Great Big World       1
Adam Lambert            2
Adele                  10
                       ..
ZAYN                    5
Zara Larsson            1
Zedd                    6
fun.                    2
will.i.am               1
Name: title, Length: 184, dtype: int64

In [45]:
df.groupby(["artist", "year"])["title"].count()

artist               year
3OH!3                2010    1
5 Seconds of Summer  2014    1
A Great Big World    2014    1
Adam Lambert         2010    2
Adele                2011    2
                            ..
Zedd                 2015    1
                     2016    1
                     2017    2
fun.                 2012    2
will.i.am            2013    1
Name: title, Length: 409, dtype: int64

In [46]:
df.head(4)

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,80,217,19,4,83
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,64,263,24,23,82
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,71,200,10,14,80
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,71,295,0,4,79

In [47]:
df.groupby(by= "artist").agg({"year": "count",
                              "dur": "mean"})

                     year    dur
artist
3OH!3                   1  192.0
5 Seconds of Summer     1  202.0
A Great Big World       1  229.0
Adam Lambert            2  227.5
Adele                  10  257.5
...                   ...    ...
ZAYN                    5  213.0
Zara Larsson            1  213.0
Zedd                    6  228.0
fun.                    2  264.0
will.i.am               1  280.0

[184 rows x 2 columns]

In [48]:
df_grouped_year = df.groupby("year")

In [49]:
df_grouped_year.ngroups

10

In [50]:
df_grouped_year.size()

year
2010    51
2011    53
2012    35
2013    71
2014    58
2015    95
2016    80
2017    65
2018    64
2019    31
dtype: int64

In [51]:
df_grouped_year.groups

{2010: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50], 2011: [51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103], 2012: [104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138], 2013: [139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209], 2014: [210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267], 2015: [268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362], 2016: [363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442], 2017: [443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507], 2018: [508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571], 2019: [572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602]}

In [52]:
df_grouped_year.get_group(2010).head(4)

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,80,217,19,4,83
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,64,263,24,23,82
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,71,200,10,14,80
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,71,295,0,4,79

## Merging datasets

In [53]:
df.head(2)

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,80,217,19,4,83
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,64,263,24,23,82

In [54]:
df2.head(2)

,Country,Continent,Rank,Title,Artists,Album,Explicit,Duration
0,Global,Global,1,Rain On Me (with Ariana Grande),"Lady Gaga, Ariana Grande",Rain On Me (with Ariana Grande),0,3:02
1,Global,Global,2,Blinding Lights,The Weeknd,After Hours,0,3:20

In [55]:
df.merge(df2, left_on="artist", right_on="Artists", how="left").fillna(0)

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,...,spch,pop,Country,Continent,Rank,Title,Artists,Album,Explicit,Duration
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,...,4,83,0,0,0.0,0,0,0,0.0,0
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,...,23,82,0,0,0.0,0,0,0,0.0,0
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,...,14,80,0,0,0.0,0,0,0,0.0,0
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,...,4,79,0,0,0.0,0,0,0,0.0,0
4,5,Just the Way You Are,Bruno Mars,pop,2010,109,84,64,-5,9,...,4,78,0,0,0.0,0,0,0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1858,599,Find U Again (feat. Camila Cabello),Mark Ronson,dance pop,2019,104,66,61,-7,20,...,3,75,0,0,0.0,0,0,0,0.0,0
1859,600,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,2019,95,79,75,-6,7,...,12,75,0,0,0.0,0,0,0,0.0,0
1860,601,"No Brainer (feat. Justin Bieber, Chance the Ra...",DJ Khaled,dance pop,2019,136,76,53,-5,9,...,34,70,0,0,0.0,0,0,0,0.0,0
1861,602,Nothing Breaks Like a Heart (feat. Miley Cyrus),Mark Ronson,dance pop,2019,114,79,60,-6,42,...,7,69,0,0,0.0,0,0,0,0.0,0
1862,603,Kills You Slowly,The Chainsmokers,electropop,2019,150,44,70,-9,13,...,6,67,0,0,0.0,0,0,0,0.0,0

In [56]:
df.merge(df2, left_on="artist", right_on="Artists", how="left", indicator=True).fillna(0)

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,...,pop,Country,Continent,Rank,Title,Artists,Album,Explicit,Duration,_merge
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,...,83,0,0,0.0,0,0,0,0.0,0,left_only
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,...,82,0,0,0.0,0,0,0,0.0,0,left_only
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,...,80,0,0,0.0,0,0,0,0.0,0,left_only
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,...,79,0,0,0.0,0,0,0,0.0,0,left_only
4,5,Just the Way You Are,Bruno Mars,pop,2010,109,84,64,-5,9,...,78,0,0,0.0,0,0,0,0.0,0,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1858,599,Find U Again (feat. Camila Cabello),Mark Ronson,dance pop,2019,104,66,61,-7,20,...,75,0,0,0.0,0,0,0,0.0,0,left_only
1859,600,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,2019,95,79,75,-6,7,...,75,0,0,0.0,0,0,0,0.0,0,left_only
1860,601,"No Brainer (feat. Justin Bieber, Chance the Ra...",DJ Khaled,dance pop,2019,136,76,53,-5,9,...,70,0,0,0.0,0,0,0,0.0,0,left_only
1861,602,Nothing Breaks Like a Heart (feat. Miley Cyrus),Mark Ronson,dance pop,2019,114,79,60,-6,42,...,69,0,0,0.0,0,0,0,0.0,0,left_only
1862,603,Kills You Slowly,The Chainsmokers,electropop,2019,150,44,70,-9,13,...,67,0,0,0.0,0,0,0,0.0,0,left_only

In [57]:
df.join(df2)

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,...,spch,pop,Country,Continent,Rank,Title,Artists,Album,Explicit,Duration
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,...,4,83,Global,Global,1,Rain On Me (with Ariana Grande),"Lady Gaga, Ariana Grande",Rain On Me (with Ariana Grande),0,3:02
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,...,23,82,Global,Global,2,Blinding Lights,The Weeknd,After Hours,0,3:20
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,...,14,80,Global,Global,3,ROCKSTAR (feat. Roddy Ricch),"DaBaby, Roddy Ricch",BLAME IT ON BABY,1,3:01
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,...,4,79,Global,Global,4,Roses - Imanbek Remix,"SAINt JHN, Imanbek",Roses (Imanbek Remix),1,2:56
4,5,Just the Way You Are,Bruno Mars,pop,2010,109,84,64,-5,9,...,4,78,Global,Global,5,Toosie Slide,Drake,Dark Lane Demo Tapes,1,4:07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598,599,Find U Again (feat. Camila Cabello),Mark Ronson,dance pop,2019,104,66,61,-7,20,...,3,75,Costa Rica,North America,49,The Box,Roddy Ricch,Please Excuse Me For Being Antisocial,1,3:16
599,600,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,2019,95,79,75,-6,7,...,12,75,Costa Rica,North America,50,CANCIÃN CON YANDEL,"Yandel, Bad Bunny",LAS QUE NO IBAN A SALIR,1,3:29
600,601,"No Brainer (feat. Justin Bieber, Chance the Ra...",DJ Khaled,dance pop,2019,136,76,53,-5,9,...,34,70,Czech Republic,Europe,1,Blinding Lights,The Weeknd,After Hours,0,3:20
601,602,Nothing Breaks Like a Heart (feat. Miley Cyrus),Mark Ronson,dance pop,2019,114,79,60,-6,42,...,7,69,Czech Republic,Europe,2,Roses - Imanbek Remix,"SAINt JHN, Imanbek",Roses (Imanbek Remix),1,2:56
602,603,Kills You Slowly,The Chainsmokers,electropop,2019,150,44,70,-9,13,...,6,67,Czech Republic,Europe,3,GOOBA,6ix9ine,GOOBA,1,2:12

In [58]:
df._append(df2).fillna(0)

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,...,spch,pop,Country,Continent,Rank,Title,Artists,Album,Explicit,Duration
0,1.0,"Hey, Soul Sister",Train,neo mellow,2010.0,97.0,89.0,67.0,-4.0,8.0,...,4.0,83.0,0,0,0.0,0,0,0,0.0,0
1,2.0,Love The Way You Lie,Eminem,detroit hip hop,2010.0,87.0,93.0,75.0,-5.0,52.0,...,23.0,82.0,0,0,0.0,0,0,0,0.0,0
2,3.0,TiK ToK,Kesha,dance pop,2010.0,120.0,84.0,76.0,-3.0,29.0,...,14.0,80.0,0,0,0.0,0,0,0,0.0,0
3,4.0,Bad Romance,Lady Gaga,dance pop,2010.0,119.0,92.0,70.0,-4.0,8.0,...,4.0,79.0,0,0,0.0,0,0,0,0.0,0
4,5.0,Just the Way You Are,Bruno Mars,pop,2010.0,109.0,84.0,64.0,-5.0,9.0,...,4.0,78.0,0,0,0.0,0,0,0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3145,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,Vietnam,Asia,46.0,ÄÃ Tá»ªNG LÃ,VÅ©.,ÄÃ Tá»ªNG LÃ,0.0,4:20
3146,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,Vietnam,Asia,47.0,MÆ°á»£n RÆ°á»£u Tá» TÃ¬nh,"BigDaddy, Emily",MÆ°á»£n RÆ°á»£u Tá» TÃ¬nh,0.0,3:18
3147,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,Vietnam,Asia,48.0,NgÃ y Táº­n Tháº¿,"TÃ³c TiÃªn, Da LAB, Touliver",NgÃ y Táº­n Tháº¿,0.0,3:52
3148,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,Vietnam,Asia,49.0,Äi Äu ÄÆ°a Äi,Bich Phuong,Äi Äu ÄÆ°a Äi,0.0,3:40
3149,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,Vietnam,Asia,50.0,Blinding Lights,The Weeknd,After Hours,0.0,3:20

## Extras

In [59]:
df.select_dtypes(include="int64").corr()

,Unnamed: 0,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
Unnamed: 0,1.000000,0.989031,-0.114849,-0.214586,0.074920,-0.133914,-0.129865,-0.129002,-0.210783,0.096518,0.013672,0.150420
year,0.989031,1.000000,-0.104247,-0.225596,0.079269,-0.126471,-0.136331,-0.122025,-0.215344,0.101725,0.004778,0.241261
bpm,-0.114849,-0.104247,1.000000,0.126170,-0.131301,0.183870,0.081579,0.016021,-0.029359,-0.113257,0.058999,0.018983
nrgy,-0.214586,-0.225596,0.126170,1.000000,0.167209,0.537528,0.186738,0.409577,-0.143610,-0.562287,0.107313,-0.057645
dnce,0.074920,0.079269,-0.131301,0.167209,1.000000,0.233170,-0.028801,0.501696,-0.176841,-0.240064,-0.028041,0.116054
dB,-0.133914,-0.126471,0.183870,0.537528,0.233170,1.000000,0.081934,0.282922,-0.104723,-0.190401,-0.001110,0.156897
live,-0.129865,-0.136331,0.081579,0.186738,-0.028801,0.081934,1.000000,0.020226,0.098339,-0.098167,0.144103,-0.075749
val,-0.129002,-0.122025,0.016021,0.409577,0.501696,0.282922,0.020226,1.000000,-0.262256,-0.249038,0.122013,0.038953
dur,-0.210783,-0.215344,-0.029359,-0.143610,-0.176841,-0.104723,0.098339,-0.262256,1.000000,0.091802,0.054564,-0.104363
acous,0.096518,0.101725,-0.113257,-0.562287,-0.240064,-0.190401,-0.098167,-0.249038,0.091802,1.000000,0.002763,0.026704
spch,0.013672,0.004778,0.058999,0.107313,-0.028041,-0.001110,0.144103,0.122013,0.054564,0.002763,1.000000,-0.041490
pop,0.150420,0.241261,0.018983,-0.057645,0.116054,0.156897,-0.075749,0.038953,-0.104363,0.026704,-0.041490,1.000000

In [60]:
(df.select_dtypes(include="int64")
 .corr()
 .style
 .background_gradient(axis=0))

In [61]:
df_grouped = df.groupby(by="artist")["title"].count()

In [62]:
df_grouped = df_grouped.to_frame()
df_grouped

                     title
artist
3OH!3                    1
5 Seconds of Summer      1
A Great Big World        1
Adam Lambert             2
Adele                   10
...                    ...
ZAYN                     5
Zara Larsson             1
Zedd                     6
fun.                     2
will.i.am                1

[184 rows x 1 columns]

In [63]:
df_grouped = df_grouped.reset_index()
df_grouped

                  artist  title
0                  3OH!3      1
1    5 Seconds of Summer      1
2      A Great Big World      1
3           Adam Lambert      2
4                  Adele     10
..                   ...    ...
179                 ZAYN      5
180         Zara Larsson      1
181                 Zedd      6
182                 fun.      2
183            will.i.am      1

[184 rows x 2 columns]

In [64]:
df_grouped2 = (df.
               groupby(by="artist")["title"]
               .count()
               .to_frame()
               .reset_index())
df_grouped2

                  artist  title
0                  3OH!3      1
1    5 Seconds of Summer      1
2      A Great Big World      1
3           Adam Lambert      2
4                  Adele     10
..                   ...    ...
179                 ZAYN      5
180         Zara Larsson      1
181                 Zedd      6
182                 fun.      2
183            will.i.am      1

[184 rows x 2 columns]

In [65]:
df[:10].style.background_gradient(axis=0)

In [66]:
df[:10].style.background_gradient(axis=0, cmap="YlOrBr")

In [67]:
df[:10].style.text_gradient(low=0.75, high=1)